apiVersion: v1
kind: Pod
metadata: 
  name: mypod
spec: 
  containers:
    - name: mycon
      image: mysql:9.4
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: configpod
        - secretRef:
            name: db-secret-pod
      volumeMounts:
        - name: config-volume
          mountPath: /var/lib/mysql
  volumes:
    - name: config-volume
      configMap:
        name: configpod
    - name: secret-volume  
      secret:
        #name: my-values
        secretName: db-secret-pod
